---
- name: test
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create demo laravel container
      docker_container:
        name: demo-laravel-container
        image: docker-test.nguyenlinh2.site/demo-laravel
        state: started
        exposed_ports:
          - 9000
        detach: true
        recreate: yes
        pull: true
        comparisons:
          image: strict
